version: '3.8'

services:
  sail-freight-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sail_freight_system
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - PORT=8000
      - HOST=0.0.0.0
      - DEBUG=True
    volumes:
      - ./app:/app/app
      - ./data:/app/data
